# Generated by Django 4.2.2 on 2023-06-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
